import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "ICAC Scoresheet",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <main className='h-full sm:h-fit sm:min-h-full w-full bg-beige-50 flex flex-col sm:rounded-lg sm:shadow-lg overflow-hidden items-center p-4 gap-2'>{children}</main>
            </body>
        </html>
    );
}
