import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "ICAC Scoresheet",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <main className='h-[100dvh] w-[100dvw] sm:w-[420px] sm:h-fit sm:my-[5dvh] mx-auto bg-beige-50 flex flex-col sm:rounded-lg sm:shadow-lg overflow-y-scroll no-scrollbar items-center px-4 py-4 gap-2'>
                    {children}
                </main>
            </body>
        </html>
    );
}
