version: '3'

services:

  backend:
    build: backend
    depends_on:
      - redis_cache
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    restart: always
    command: sh -c "npm install && npm run dev"
    volumes:
      - type: bind
        source: ./frontend
        target: /app/
      # override bind mount by specifying as Docker-managed volumes
      - /app/node_modules   # persisting as bind mount will populate the container with OS-specific packages
      - /app/.next          # persisting as bind mount will populate the container with OS-specific artefacts
  
  match_server:
    build: match_server
    ports:
      - "3030:3030"
    depends_on:
      - redis_cache
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./match_server:/app
      - /app/node_modules

  redis_cache:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
  
  nginx:
    image: 'nginx'
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - '8001:80'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
