version: '3'

services:

  backend:
    build:
      dockerfile: Dockerfile
      target: prod
      context: backend
    ports:
      - "3001:3001"
    command: >
      sh -c "npm run db-setup && npm run start"
    env_file:
      - backend/.env.production
    environment:
      - HOST_DOMAIN=http://localhost

  match_server:
    build:
      context: match_server
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3030:3030"
    env_file:
      - match_server/.env.production
    environment:
      - SESSION_EXPIRY=15
      - HOST_DOMAIN=http://localhost
      - PORT=3030

  frontend:
    build:
      dockerfile: Dockerfile
      target: nextprod
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    restart: always

  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx
    restart: always
    depends_on:
      - frontend
      - backend
      - match_server
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf