version: '3'

services:

  backend:
    image: levurmion/icac-scoresheet:backend-arm64-v1.0
    ports:
      - "3001:3001"
    command: >
      sh -c "npm run db-setup && npm run start"
    env_file:
      - ./backend/.env.production
    environment:
      - HOST_DOMAIN=icac-scoresheet.com

  match_server_1:
    image: levurmion/icac-scoresheet:match-server-arm64-v1.0
    ports:
      - "3030:3030"
    env_file:
      - ./match_server/.env.production
    environment:
      - SESSION_EXPIRY=15
      - HOST_DOMAIN=icac-scoresheet.com
      - PORT=3030
  
  match_server_2:
    image: levurmion/icac-scoresheet:match-server-arm64-v1.0
    ports:
      - "3031:3031"
    env_file:
      - ./match_server/.env.production
    environment:
      - SESSION_EXPIRY=15
      - HOST_DOMAIN=icac-scoresheet.com
      - PORT=3031
  
  frontend:
    image: levurmion/icac-scoresheet:frontend-arm64-v1.0
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
      - ./frontend/.env.production
    restart: always

  nginx:
    image: levurmion/icac-scoresheet:nginx-arm64-v1.0
    restart: always
    depends_on:
      - frontend
      - backend
      - match_server_1
      - match_server_2
    ports:
      - '80:80'