version: '3'

services:

  backend:
    build:
      dockerfile: Dockerfile
      target: dev
      context: backend
    depends_on:
      - redis
    ports:
      - "3001:3001"
    command: >
      sh -c "npm install &&
            npm run db-setup-dev &&
            npm run dev"
    env_file:
      - backend/.env.development
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.development
    restart: always
    command: sh -c "npm install && npm run dev"
    volumes:
      - type: bind
        source: ./frontend
        target: /app/
      # override bind mount by specifying as Docker-managed volumes
      - /app/node_modules   # persisting as bind mount will populate the container with OS-specific packages
      - /app/.next          # persisting as bind mount will populate the container with OS-specific artefacts
  
  match_server:
    build:
      context: match_server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3030:3030"
    depends_on:
      - redis
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./match_server:/app
      - /app/node_modules
    env_file:
      - match_server/.env.development
    environment:
      - PORT=3030
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis/redis.conf
    command: "redis-server /redis/redis.conf"

  nginx:
    image: 'nginx'
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - match_server
    ports:
      - '80:80'
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
