version: '3'

services:

  backend:
    build: backend
    depends_on:
      - redis_cache
    ports:
      - "3001:3001"
    volumes:
      # bind mount the distributable Typescript JS output
      - type: bind
        source: ./backend/dist
        target: /app/dist/
  
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - type: bind
        source: ./frontend
        target: /app/
      # override bind mount by specifying as Docker-managed volumes
      - /app/node_modules   # persisting as bind mount will populate the container with OS-specific packages
      - /app/.next          # persisting as bind mount will populate the container with OS-specific artefacts

  redis_cache:
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379:6379"
