name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['backend', 'frontend', 'match_server']
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: service_changed
        with:
          filters: |
            src:
              - '${{ matrix.service }}/src/**'
            deps:
              - '${{ matrix.service }}/package*.json'
      - name: Rebuild ${{ matrix.service }}
        if: steps.service_changed.outputs.src == 'true' || steps.service_changed.outputs.deps == 'true'
        run: |
          cd ./${{ matrix.service }}
          docker build . --platform linux/arm64 --tag levurmion/icac-scoresheet:${{ matrix.service }}-latest
      - name: Set docker build status
        id: docker_build_status
        run: |
          echo "STATUS=${{ steps.docker-build.outcome }}" >> "$GITHUB_OUTPUT"
      - name: Log in to Docker Hub
        if: steps.docker_build_status.outputs.STATUS == 'success'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        if: steps.docker_build_status.outputs.STATUS == 'success'
        run: docker push levurmion/icac-scoresheet:${{ matrix.service }}-latest

