name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['backend', 'frontend', 'match_server']
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: service_changed
      with:
        filters: |
          src:
            - '${{ matrix.service }}/src/**'
          deps:
            - '${{ matrix.service }}/package*.json'
    # only run build if changes were detected
    - name: Rebuild ${{ matrix.service }}
      if: steps.service_changed.outputs.src == 'true' || steps.service_changed.outputs.deps == 'true'
      # run docker build and save exit status
      run: |
        docker build ${{ matrix.service }} --file Dockerfile --platform linux/arm64 --tag levurmion/icac-scoresheet:${{ matrix.service }}-latest
        echo "DOCKER_BUILD_STATUS=$?" >> $GITHUB_ENV
    # login to docker hub
    - name: Log in to Docker Hub
      if: env.DOCKER_BUILD_STATUS == '0'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # push to docker hub
    - name: Push to Docker Hub
      if: env.DOCKER_BUILD_STATUS == '0'
      run: |
        docker push levurmion/icac-scoresheet:${{ matrix.service }}-latest
